cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_cart/<int:id>/', views.add_cart, name='add_cart'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:book_id>/', views.full_remove, name='full_remove'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

my_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mylibrary.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mylibrary/urls.py
from django.urls import path

from mylibrary.views import *

app_name = 'mylibrary'

urlpatterns = [
    path('', home, name='home'),
    path('book/<int:id>/', detail_view, name='detail'),
    path('add_book/', add_book, name='add_book'),
    path('update/<int:id>/', update_book, name='update'),
    path('delete/<int:id>/', delete_book, name='delete'),
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('add_patron/', add_patrons, name='add_patron'),
    path('all_patrons/', all_patrons, name='all_patrons'),
    path('update_patron/<int:id>/', update_patron, name='update_patron'),
    path('delete_patron/<int:id>/', delete_patron, name='delete_patron'),
    path('newspaper/', news_paper, name='newspaper'),
    path('program/<int:id>/', programmes, name='program'),
    path('category/', all_book_category, name='all_book_category'),
    path('category/<slug:c_slug>/', all_book_category, name='books_by_category'),

]

search_app/urls.py
from django.urls import path

from mylibrary.views import *
from search_app import views

app_name = 'search_app'

urlpatterns = [
    path('', views.search_result, name='search'),
    path('patron/', views.patrons, name='patron'),
    path('superuser/', superuser, name='superuser'),
    path('add_notification/', add_notifications, name='add_notify'),
    path('download/<int:notification_id>/', download_card, name='download_page'),
    path('download/<int:notification_id>/', download_card, name='download'),
    path('update_notification/<int:id>/', update_notify, name='update_notify'),
    path('update_news/<int:id>/', update_news, name='update_news'),
    path('delete_notification/<int:id>/', delete_notify, name='delete_notify'),
    path('issue_patron/<int:id>/', issue_patron, name='issue_patron'),
    path('return_patron/<int:id>/', return_patron, name='return_patron'),
    path('renew_patron/<int:id>/', renew_patron, name='renew_patron'),
    path('return_all_books/<int:id>/', return_all_books, name='return_all_books'),
    path('renew_all_books/<int:id>/', renew_all_books, name='renew_all_books'),
    path('pay_all_fine/<int:id>/', pay_all_fine, name='pay_all_fine'),
    path('pay_fine/<int:id>/', pay_fine, name='pay_fine'),
    path('all_history/', all_history, name='all_history'),
    path('history/', history, name='history'),
    path('add_category/', add_category, name='add_category'),
    path('add_language/', add_language, name='add_language'),
    path('add_newspaper/', add_newspaper, name='add_newspaper'),
    path('delete_category/<int:id>/', delete_category, name="delete_category"),
    path('delete_language/<int:id>/', delete_language, name="delete_language"),
    path('delete_newspaper/<int:id>/', delete_newspaper, name="delete_newspaper"),
    path('all_programmes/', all_programmes, name='all_programmes'),
    path('profile/<int:id>/', profile, name='profile'),
    path('language/<slug:l_slug>/', all_book_language, name='books_by_language'),
    path('language/', all_book_language, name='all_book_language'),

]

cart/models.py
from django.db import models
from mylibrary.models import Book_details


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    book = models.ForeignKey(Book_details, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.book.price * self.quantity

    def __str__(self):
        return '{}'.format(self.book)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from mylibrary.models import Book_details
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, id):
    book = Book_details.objects.get(id=id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(book=book, cart=cart)
        if cart_item.quantity < cart_item.book.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            book=book,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')


def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.book.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, book_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    book = get_object_or_404(Book_details, id=book_id)
    cart_item = CartItem.objects.get(book=book, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')


def full_remove(request, book_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    book = get_object_or_404(Book_details, id=book_id)
    cart_item = CartItem.objects.get(book=book, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')


def clear_cart(request):
    # Clear the cart items and set the amount to zero
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart)
    cart_items.delete()

    # Redirect back to the cart details page
    return redirect('cart:cart_details')

templates/all_patrons.html
{% extends 'base.html' %}
{% block body %}
<title>{% block title %}all patron{% endblock %}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.0.7/css/boxicons.min.css">
<style>
 body{
background: #eff3f6;
}
.thumb-lg {
height: 88px;
width: 88px;
}
.card {
border: none;
box-shadow: 1px 0px 20px rgba(0, 0, 0, 0.05);
}
.m-b-30 {
margin-bottom: 30px;
}
.social-links li a {
-webkit-border-radius: 50%;
background: #fcfdfd;
border-radius: 50%;
color: #9f9f9f;
display: inline-block;
height: 30px;
line-height: 30px;
text-align: center;
width: 30px;
}

</style>
<br><br>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12 ">
            <div>
                <form action="{% url 'search_app:patron' %}" class="search-bar">
                    <input aria-label="Search" class="" name="q" placeholder="Search {{ patron_count }} patrons..."
                           type="search">
                    <button class="btn btn-light" type="submit" >
                        <i class="fa-solid fa-magnifying-glass fa-xl fa-beat"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div><br><br>
<div class="col-lg-12">
    <div class="row">
        {% for i in patron %}
        <div class="col-lg-3 p-1">
            <div class="card">
                <div class="card-body text-center">
                    <div class="media">
                        <img class="rounded-circle img-thumbnail thumb-lg"
                             src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="Generic placeholder image"/>
                        <div class="media-body"><br>
                            <h4 class="mt-0 font-18 mb-1 text-uppercase"><b>{{i.name}}</b></h4>
                            <p class="text-muted font-16"><b>{{i.card_no}}</b></p>
                            <div>
                                <a class="btn btn-info" href="{% url 'search_app:profile' i.id %}">USER</a>
                                <a class="btn btn-dark" href="{% url 'search_app:issue_patron' i.id %}">ISSUE</a>
                                <a class="btn btn-success" href="{% url 'search_app:return_patron' i.id %}">RETURN</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
<html>
<head>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
{% include 'nav.html' %}
{% block body %}
{% endblock %}
{% block metadescription %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

templates/category.html
{% extends 'base.html' %}
{% block title %}
{% if category %}
{{category.name}}
{% else %}
my library
{% endif %}
{% endblock %}
{% block body %}
{% endblock %}
{% block metadescription %}
{% if category %}
<style>
    {% for book in books %}
    .category-color-{{ forloop.counter }} {
        background-color: {% cycle '#FF3366' '#FF9900' '#FFCC00' '#66CC00' '#00CCCC' '#3399FF' '#9933FF' '#FF33CC' '#FF6666' '#FFCC99' '#99CC99' '#66CCCC' %};
    }
    {% endfor %}
     @media screen and (max-width: 600px) {
        .book_1 {
             max-width: 40%;
        }
        .book_2 {
             max-width: 58%;
        }
    }
</style>
<br>
<h1 class="text-center text-dark text-uppercase">
    {{ category.name|truncatewords:155 }}
</h1>
{% else %}
<br>
<h1 class="text-center text-dark text-uppercase">
    ALL CATEGORIES
</h1>
{% endif %}
<style>
    {% for book in books %}
    .category-color-{{ forloop.counter }} {
        background-color: {% cycle '#FF3366' '#FF9900' '#FFCC00' '#66CC00' '#00CCCC' '#3399FF' '#9933FF' '#FF33CC' '#FF6666' '#FFCC99' '#99CC99' '#66CCCC' %};
    }
    {% endfor %}
.source-1 {
  src: 'https://bootdey.com/img/Content/avatar/avatar7.png';
}

.source-2 {
  src: 'https://bootdey.com/img/Content/avatar/avatar6.png';
}
 @media screen and (max-width: 600px) {

        .book_1 {
             max-width: 40%;
        }
        .book_2 {
             max-width: 58%;
        }
    }
</style>
<br><br>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12 ">
            <div>
                <form action="{% url 'search_app:search' %}" class="search-bar">
                    <input aria-label="Search" class="" name="q" placeholder="Search {{ book_count }} books..."
                           type="search">
                    <button class="btn btn-light" type="submit" >
                        <i class="fa-solid fa-magnifying-glass fa-xl fa-beat"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<br><br>
<div class="col-md-12">
    <div class="row">
        {% for book in books %}
        <div class=" col-md-1 book_1"><br>
            <div style="border-radius: 10px;" class=" text-center radius:20px category-color-{{ forloop.counter }}">
                <b>{{book.primary_number}}</b>
            </div>
            <img alt="{{ book.name }}" class="card-img"
                 src="https://creazilla-store.fra1.digitaloceanspaces.com/emojis/48096/orange-book-emoji-clipart-md.png"
                 style="border-radius: 20px; height:200px; width: 180px;">
        </div>
        <a class="text-dark" href="{% url 'mylibrary:detail' book.id %}" style="text-decoration: none;">
            <div class="card col-md-2 text-center book_2">
                <div class="card-body">
                    <h6 class="card-title text-uppercase"><b>{{ book.name }}</b></h6>
                    <p class="card-text text-uppercase">({{ book.author }} )</p>
                    <p class="card-text text-uppercase text-left">CATEGORY: {{ book.category.name }} </p>
                    <p class="card-text text-uppercase text-left">LANGUAGE: {{ book.lang }}</p>
                    <p class="card-text text-uppercase text-left">PRICE: <i class="fa fa-rupee"></i> {{ book.price }}
                    </p>
                    <a class="btn btn-primary" href="{% url 'mylibrary:detail' book.id %}">
                        More <i class="fa-sharp fa-solid fa-angles-right"></i>
                    </a>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
<br>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="card" style="background: white">
                <h2 class=" text-center" style="padding:15px"><b>MYLIBRARY</b></h2>
                <div class="card-body">
                    <p>
                        Hi How Are You ?<br><br>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The word library is derived from a French word "Librairie";
                        Latin "liber" = book. The library plays an important role in our academic and social lives.
                        Library is an organized collection of information resources made accessible to a defined
                        community for reference or borrowing and this collection of information may be in the form of
                        books, newspapers, CD’s, journals and research papers etc. library provides us physical or
                        digital access to material, and may be a physical building or room, or a virtual space, or both
                        containing collection of informative material.
                        <br><br>
                    <div class="text-center">
                        <b class="text-center">Now Available Categories</b>
                        <hr style="background: #000">
                        {% for category in links %}
                        <i class="text-uppercase">{{ category.name }},</i>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/language.html
{% extends 'base.html' %}
{% block title %}
{% if language %}
{{language.name}}
{% else %}
my library
{% endif %}
{% endblock %}
{% block body %}
{% endblock %}
{% block metadescription %}
{% if language %}
<style>
    {% for book in books %}
    .category-color-{{ forloop.counter }} {
        background-color: {% cycle '#FF3366' '#FF9900' '#FFCC00' '#66CC00' '#00CCCC' '#3399FF' '#9933FF' '#FF33CC' '#FF6666' '#FFCC99' '#99CC99' '#66CCCC' %};
    }
    {% endfor %}
     @media screen and (max-width: 600px) {
        .col-lg-2 {
            flex: 0 0 100%; /* Force each column to occupy the full width */
            max-width: 50%;
        }
        .book_1 {
             max-width: 40%;
        }
        .book_2 {
             max-width: 58%;
        }
    }
</style>
<br>
<h1 class="text-center text-dark text-uppercase">
    {{ language.name|truncatewords:155 }}
</h1>
{% else %}
<br>
<h1 class="text-center text-dark text-uppercase">
    ALL LANGUAGES
</h1>
{% endif %}
<style>
    {% for book in books %}
    .category-color-{{ forloop.counter }} {
        background-color: {% cycle '#FF3366' '#FF9900' '#FFCC00' '#66CC00' '#00CCCC' '#3399FF' '#9933FF' '#FF33CC' '#FF6666' '#FFCC99' '#99CC99' '#66CCCC' %};
    }
    {% endfor %}
.source-1 {
  src: 'https://bootdey.com/img/Content/avatar/avatar7.png';
}

.source-2 {
  src: 'https://bootdey.com/img/Content/avatar/avatar6.png';
}
 @media screen and (max-width: 600px) {
        .col-lg-2 {
            flex: 0 0 100%; /* Force each column to occupy the full width */
            max-width: 50%;
        }
        .book_1 {
             max-width: 40%;
        }
        .book_2 {
             max-width: 58%;
        }
    }
</style>
<br><br>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12 ">
            <div>
                <form action="{% url 'search_app:search' %}" class="search-bar">
                    <input aria-label="Search" class="" name="q" placeholder="Search {{ book_count }} books..."
                           type="search">
                    <button class="btn btn-light" type="submit" >
                        <i class="fa-solid fa-magnifying-glass fa-xl fa-beat"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<br><br>
<div class="col-md-12">
    <div class="row">
        {% for book in books %}
        <div class=" col-md-1 book_1"><br>
            <div style="border-radius: 10px;" class=" text-center radius:20px category-color-{{ forloop.counter }}">
                <b>{{book.primary_number}}</b>
            </div>
            <img alt="{{ book.name }}" class="card-img"
                 src="https://creazilla-store.fra1.digitaloceanspaces.com/emojis/48096/orange-book-emoji-clipart-md.png"
                 style="border-radius: 20px; height:200px; width: 180px;">
        </div>
        <a class="text-dark" href="{% url 'mylibrary:detail' book.id %}" style="text-decoration: none;">
            <div class="card col-md-2 text-center book_2">
                <div class="card-body">
                    <h6 class="card-title text-uppercase"><b>{{ book.name }}</b></h6>
                    <p class="card-text text-uppercase">({{ book.author }} )</p>
                    <p class="card-text text-uppercase text-left">CATEGORY: {{ book.category.name }} </p>
                    <p class="card-text text-uppercase text-left">LANGUAGE: {{ book.lang }}</p>
                    <p class="card-text text-uppercase text-left">PRICE: <i class="fa fa-rupee"></i> {{ book.price }}
                    </p>
                    <a class="btn btn-primary" href="{% url 'mylibrary:detail' book.id %}">
                        More <i class="fa-sharp fa-solid fa-angles-right"></i>
                    </a>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
<br>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="card" style="background: white">
                <h2 class=" text-center" style="padding:15px"><b>MYLIBRARY</b></h2>
                <div class="card-body">
                    <p>
                        Hi How Are You ?<br><br>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The word library is derived from a French word "Librairie";
                        Latin "liber" = book. The library plays an important role in our academic and social lives.
                        Library is an organized collection of information resources made accessible to a defined
                        community for reference or borrowing and this collection of information may be in the form of
                        books, newspapers, CD’s, journals and research papers etc. library provides us physical or
                        digital access to material, and may be a physical building or room, or a virtual space, or both
                        containing collection of informative material.
                        <br><br>
                    <div class="text-center">
                        <b class="text-center">Now Available Categories</b>
                        <hr style="background: #000">
                        {% for category in links %}
                        <i class="text-uppercase">{{ category.name }},</i>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/news paper.html
{% extends 'base.html' %}
{% block body %}
<title>{% block title %}my library{% endblock %}</title>
<style>
.newspaper-cards {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.newspaper-card {
  flex: 0 0 calc(33.33% - 20px);
  margin: 10px;
  padding: 20px;
  background-color: #f5f5f5;
  border-radius: 5px;
  text-align: center;
}

.newspaper-card a {
  text-decoration: none;
  color: #333;
}

.newspaper-card img {
  width: 100%;
  max-height: 200px;
  object-fit: cover;
}

.newspaper-card h4 {
  margin-top: 10px;
}
@media screen and (max-width: 600px){
    .col-md-3{
        width: 50%;
    }
}

</style>
<div class="col-md-12">
    <div class="row">
        {% for news in newspaper %}
        <div class="col-md-3 p-1">
            <div class="cards">
                <div class="newspaper-card align-items-center">
                    <a href="{{ news.pdf.url }}" target="_blank">
                        <img src="https://static.vecteezy.com/system/resources/previews/012/665/107/original/simple-cartoon-illustration-of-an-open-newspaper-office-concept-vector.jpg"
                             alt="{{ news.name }}"><br><br>
                        <h6 class="text-uppercase"><b>{{ news.name }}<br> [ 0{{ forloop.counter }} ]</b></h6>
                    </a>
                    <div class="text-center">
                        <a href="{{ news.pdf.url }}" class="btn btn-info text-white"><b>READ</b></a>
                    <a href="{{ news.pdf.url }}" class="btn btn-success text-white" download><b>HERE <i class="fas fa-download"></i> </b></a><br><br>
                    <a href="{% url 'search_app:delete_newspaper' news.id %}" class="btn btn-secondary text-white"><b>DELETE </b></a>
                    <a href="{% url 'search_app:update_news' news.id %}" class="btn btn-warning text-white"><b>UPDATE</b></a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

templates/programmes.html
{% extends 'base.html' %}
{% block body %}
<title>{% block title %}programs{% endblock %}</title>
<style>
    @media screen and (max-width: 600px){
        .notify{
            width: 50%;
        }
    }
</style>
{% if msg %}
<body><br>
<div class="col-md-12">
    <div class="col-md-12">
        <div class="row">
            <div class="card col-md-12 l-bg-green">
                <br>
                <div class="card bg-light text-center text-dark text-uppercase"><br><h4><b>{{ msg.name }}</b></h4><br></div>
                <div class="card-body ">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card-content">
                                <h4 class="card-title">On<b>:</b></h4>
                                <p class="text-uppercase">{{ msg.on }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Location</h4>
                                <p class="text-uppercase">{{ msg.location }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Inauguration</h4>
                                <p class="text-uppercase">{{ msg.inauguration }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Welcome speech</h4>
                                <p class="text-uppercase">{{ msg.welcome_speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Presidential Speech</h4>
                                <p class="text-uppercase">{{ msg.presidential_speech }}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-content">
                                <h4 class="card-title">Greetings</h4>
                                <p class="text-uppercase">{{ msg.greetings }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Special Speech</h4>
                                <p class="text-uppercase">{{ msg.special_speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Speech</h4>
                                <p class="text-uppercase">{{ msg.speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Song</h4>
                                <p class="text-uppercase">{{ msg.song }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Vote of Thanks</h4>
                                <p class="text-uppercase">{{ msg.vote_of_thanks }}</p>
                            </div>
                            <br>
                        </div>
                        <div class="col-md-4">
                            <a href="" download="img.jpg"><img
                                    src="https://assets.stickpng.com/images/580b585b2edbce24c47b276e.png"
                                    alt="Image" class="img-fluid" height="300px"
                                    width="300px"></a>
                            <div class="card-content text-center">
                                <a href="{% url 'search_app:delete_notify' msg.id %}" class="btn btn-danger">DELETE</a>
                                &nbsp;
                                <a href="{% url 'search_app:update_notify' msg.id %}" class="btn btn-info">UPDATE</a>
                                &nbsp;<br><br>
                                <a href="{% url 'search_app:download_page' msg.id %}" class="btn btn-secondary"
                                   download>DOWNLOAD</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% else %}
<body><br>
<div class="col-md-12">
    <div class="col-md-12">
        <div class="row">
            {% for all_msg in all_msg %}
            <div class="card col-md-12 l-bg-green ">
                <br>
                <div class="card bg-light text-center text-dark text-uppercase"><br><h4><b>{{ all_msg.name }}</b></h4><br></div>
                <div class="card-body ">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card-content">
                                <h4 class="card-title">On<b>:</b></h4>
                                <p class="text-uppercase">{{ all_msg.on }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Location</h4>
                                <p class="text-uppercase">{{ all_msg.location }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Inauguration</h4>
                                <p class="text-uppercase">{{ all_msg.inauguration }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Welcome speech</h4>
                                <p class="text-uppercase">{{ all_msg.welcome_speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Presidential Speech</h4>
                                <p class="text-uppercase">{{ all_msg.presidential_speech }}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-content">
                                <h4 class="card-title">Greetings</h4>
                                <p class="text-uppercase">{{ all_msg.greetings }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Special Speech</h4>
                                <p class="text-uppercase">{{ all_msg.special_speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Speech</h4>
                                <p class="text-uppercase">{{ all_msg.speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Song</h4>
                                <p class="text-uppercase">{{ all_msg.song }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Vote of Thanks</h4>
                                <p class="text-uppercase">{{ all_msg.vote_of_thanks }}</p>
                            </div>
                            <br>
                        </div>
                        <div class="col-md-4">
                            <a href="" download="img.jpg"><img
                                    src="https://assets.stickpng.com/images/580b585b2edbce24c47b276e.png"
                                    alt="Image" class="img-fluid" height="300px"
                                    width="300px"></a>
                            <div class="card-content text-center">
                                <a href="{% url 'search_app:delete_notify' all_msg.id %}"
                                   class="btn btn-danger">DELETE</a>
                                &nbsp;
                                <a href="{% url 'search_app:update_notify' all_msg.id %}"
                                   class="btn btn-info">UPDATE</a>
                                &nbsp;<br><br>
                                <a href="{% url 'search_app:download_page' all_msg.id %}" class="btn btn-secondary"
                                   download>DOWNLOAD</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</body>
{% endif %}
{% endblock %}